spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/propertydb
    username: postgres
    password: SuperSecret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

pms:
  dummy: This is a dummy for LOCAL environment